### PR TITLE
Replace indmax -> argmax

### PR DESCRIPTION
**Pull request by drozzy**

### CODE REVIEW

**Review by johnnychen94 — APPROVED** [review]
Thanks for updating it!

**Comment by johnnychen94** [comment]
@Evizero Do you still remember how the docs get updated? I couldn't find the `gh-pages` branch in this repo.

**Comment by Evizero** [comment]
This package is old enough that it still uses readthedocs, which is not hosted by github itself and i think it was triggered by webhooks

**Comment by johnnychen94** [comment]
Seems like it has been updated automatically, great!

**Pull request merged**
